swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /member/:
    get:
      tags:
      - member
      description: get Member
      operationId: MemberController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Member'
        "403":
          description: ""
    post:
      tags:
      - member
      description: create Member
      operationId: MemberController.Post
      parameters:
      - in: body
        name: body
        description: body for Member content
        required: true
        schema:
          $ref: '#/definitions/models.Member'
      responses:
        "201":
          description: '{int} models.Member'
        "403":
          description: body is empty
  /member/{id}:
    get:
      tags:
      - member
      description: get Member by id
      operationId: MemberController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Member'
        "403":
          description: :id is empty
    put:
      tags:
      - member
      description: update the Member
      operationId: MemberController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Member content
        required: true
        schema:
          $ref: '#/definitions/models.Member'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Member'
        "403":
          description: :id is not int
    delete:
      tags:
      - member
      description: delete the Member
      operationId: MemberController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Member:
    title: Member
    type: object
    properties:
      Alamat:
        type: string
      CodeMember:
        type: string
      Company:
        type: string
      Email:
        type: string
      Gender:
        type: string
      Id:
        type: integer
        format: int64
      NamaMember:
        type: string
      Phone:
        type: string
      StatusAccount:
        type: string
tags:
- name: member
  description: |
    MemberController operations for Member
